#!/usr/bin/env python3

import argparse
from datetime import datetime, timezone
import getpass
import json
import os
from pathlib import Path
import re
import secrets
import tempfile
from urllib.parse import parse_qs, urlsplit

from azure.ai.projects import AIProjectClient
from azure.identity import AzureCliCredential


ROOT = Path(__file__).resolve().parent.parent
GATEWAY_DIR = Path(__file__).resolve().parent
DEFAULT_ENV_FILE = GATEWAY_DIR / ".env"
ENV_KEY = re.compile(r"^[A-Z][A-Z0-9_]*$")


def parse_env(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}

    values: dict[str, str] = {}
    for line_number, raw_line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].lstrip()
        if "=" not in line:
            raise ValueError(f"{path}:{line_number}: expected KEY=VALUE")
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not ENV_KEY.fullmatch(key):
            raise ValueError(f"{path}:{line_number}: invalid environment variable name")
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        values[key] = value
    return values


def quote_env(value: str) -> str:
    if "\n" in value or "\r" in value or "'" in value:
        raise ValueError("Environment values must be single-line and cannot contain a single quote")
    return f"'{value}'"


def find_build_info(explicit_path: str | None) -> Path:
    if explicit_path:
        path = Path(explicit_path).expanduser().resolve()
        if not path.is_file():
            raise FileNotFoundError(f"Build metadata not found: {path}")
        return path

    matches = sorted(ROOT.glob("build_info-*.json"))
    if len(matches) != 1:
        raise RuntimeError(
            f"Expected exactly one build_info-*.json in {ROOT}; found {len(matches)}"
        )
    return matches[0]


def validate_neon_url(value: str) -> str:
    if not value or "REPLACE_WITH" in value:
        raise ValueError(
            "DATABASE_URL is missing. Add a direct Neon connection string to gateway/.env."
        )
    parsed = urlsplit(value)
    if parsed.scheme not in {"postgres", "postgresql"} or not parsed.hostname:
        raise ValueError("DATABASE_URL must be a PostgreSQL connection URL")
    if not parsed.hostname.endswith(".neon.tech"):
        raise ValueError("DATABASE_URL must target a Neon hostname ending in .neon.tech")
    if "-pooler." in parsed.hostname:
        raise ValueError(
            "Use a direct Neon endpoint for LiteLLM startup migrations, not a -pooler hostname"
        )
    if parse_qs(parsed.query).get("sslmode", [None])[-1] not in {"require", "verify-full"}:
        raise ValueError("DATABASE_URL must enforce TLS with sslmode=require or verify-full")
    return value


def resolve_database_url(
    current: dict[str, str], source_path: str | None,
) -> str:
    source = parse_env(Path(source_path).expanduser().resolve()) if source_path else {}
    candidate = (
        source.get("DATABASE_URL_UNPOOLED")
        or source.get("DATABASE_URL")
        or current.get("DATABASE_URL")
        or ""
    )
    return validate_neon_url(candidate)


def write_env(path: Path, values: dict[str, str]) -> None:
    lines = [
        "# Generated by gateway/refresh_runtime_env.py. Do not commit.",
        *(f"{key}={quote_env(value)}" for key, value in values.items()),
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(prefix=".env.", dir=path.parent, text=True)
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as stream:
            stream.write("\n".join(lines))
        os.chmod(temporary_path, 0o600)
        temporary_path.replace(path)
    finally:
        if temporary_path.exists():
            temporary_path.unlink()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Refresh the Foundry endpoint, Entra token, and local LiteLLM secrets."
    )
    parser.add_argument("--build-info")
    database_source = parser.add_mutually_exclusive_group()
    database_source.add_argument("--database-env-source")
    database_source.add_argument(
        "--prompt-database-url",
        action="store_true",
        help="Prompt, without echo, for a direct Neon connection string.",
    )
    parser.add_argument("--env-file", default=str(DEFAULT_ENV_FILE))
    args = parser.parse_args()

    env_path = Path(args.env_file).expanduser().resolve()
    current = parse_env(env_path)
    if args.prompt_database_url:
        database_url = validate_neon_url(
            getpass.getpass("Paste the direct Neon connection string: ").strip()
        )
    else:
        database_url = resolve_database_url(current, args.database_env_source)

    build_path = find_build_info(args.build_info)
    build_info = json.loads(build_path.read_text(encoding="utf-8"))
    if build_info.get("agent_invocation_mode") != "agent_endpoint":
        raise ValueError("The Linux notebook must use agent_endpoint mode")
    backend_agents = build_info.get("backend_agents", {})

    credential = AzureCliCredential()
    project_client = AIProjectClient(
        endpoint=build_info["foundry_project_endpoint"],
        credential=credential,
        allow_preview=True,
    )
    agent_base_urls = {}
    for role in ("main", "sentinel"):
        agent_name = backend_agents.get(role, {}).get("name")
        if not isinstance(agent_name, str) or not agent_name:
            raise ValueError(f"Build metadata does not define backend_agents.{role}.name")
        agent = project_client.agents.get(agent_name=agent_name)
        if agent.state != "enabled":
            raise RuntimeError(f"Foundry agent {agent_name} is not enabled")
        openai_client = project_client.get_openai_client(agent_name=agent_name)
        agent_base_urls[role] = (agent_name, str(openai_client.base_url).rstrip("/"))
    access_token = credential.get_token("https://ai.azure.com/.default")

    values = {
        "DATABASE_URL": database_url,
        "LITELLM_MASTER_KEY": current.get("LITELLM_MASTER_KEY")
        or f"sk-{secrets.token_hex(32)}",
        "LITELLM_SALT_KEY": current.get("LITELLM_SALT_KEY")
        or f"sk-{secrets.token_hex(32)}",
        "FOUNDRY_MAIN_AGENT_BASE_URL": agent_base_urls["main"][1],
        "FOUNDRY_SENTINEL_AGENT_BASE_URL": agent_base_urls["sentinel"][1],
        "AZURE_AD_TOKEN": access_token.token,
        "AZURE_AD_TOKEN_EXPIRES_ON": datetime.fromtimestamp(
            access_token.expires_on, timezone.utc,
        ).isoformat(),
        "LITELLM_BIND_ADDRESS": current.get("LITELLM_BIND_ADDRESS", "127.0.0.1"),
        "LITELLM_PORT": current.get("LITELLM_PORT", "4000"),
    }
    write_env(env_path, values)
    print(f"Refreshed {env_path}")
    for role, (agent_name, _) in agent_base_urls.items():
        print(f"Foundry {role} agent: {agent_name}")
    print(f"Azure token expires at {values['AZURE_AD_TOKEN_EXPIRES_ON']}")


if __name__ == "__main__":
    main()
