// ════════════════════════════════════════════════════════════════
// main.bicep — Subscription-scoped entry point
// Creates the <prefix>-<suffix> resource group and deploys all
// AI Foundry resources + RBAC via the resources module.
// ════════════════════════════════════════════════════════════════
targetScope = 'subscription'

@description('Object ID of the zolab-ai-dev Entra ID security group')
param aiDevGroupObjectId string

@description('Subscription ID of the Security subscription (hosts LAW)')
param securitySubscriptionId string

@description('6-char alphanumeric suffix for resource naming (generated by deploy script)')
param suffix string

@description('Deployment name to create for the selected AI model')
param aiModelDeploymentName string

@description('AI model name resolved for the selected deployment')
param aiModelName string

@description('Model format resolved for the selected deployment')
param aiModelFormat string

@description('Azure OpenAI model version resolved for the selected deployment')
param aiModelVersion string

@description('SKU name for the selected AI model deployment')
param aiModelSkuName string

@description('SKU capacity for the selected AI model deployment')
param aiModelSkuCapacity int

@description('Location for all resources')
param location string = 'eastus2'

// ── Naming ──
@description('Prefix for the resource group name (result: <prefix>-<suffix>)')
param resourceGroupPrefix string = 'zolab-ai'

@description('Prefix used to construct all child resource names')
param namePrefix string = 'zolabai'

// ── Log Analytics Workspace (cross-subscription) ──
@description('Resource group containing the Log Analytics Workspace')
param lawResourceGroup string = 'Sentinel'

@description('Name of the Log Analytics Workspace')
param lawWorkspaceName string = 'DIBSecCom'

// ── SKUs & Retention ──
@description('Storage account SKU')
param storageSkuName string = 'Standard_LRS'

@description('Storage account access tier')
param storageAccessTier string = 'Hot'

@description('Key Vault soft-delete retention in days')
param kvSoftDeleteRetentionDays int = 7

@description('Application Insights retention in days')
param appInsightsRetentionDays int = 90

@description('AI Foundry (Cognitive Services) SKU')
param aiServicesSkuName string = 'S0'

// ── Derived ──
var resourceGroupName = '${resourceGroupPrefix}-${suffix}'
var logAnalyticsWorkspaceId = '/subscriptions/${securitySubscriptionId}/resourceGroups/${lawResourceGroup}/providers/Microsoft.OperationalInsights/workspaces/${lawWorkspaceName}'

resource rg 'Microsoft.Resources/resourceGroups@2024-11-01' = {
  name: resourceGroupName
  location: location
}

module resources 'modules/resources.bicep' = {
  name: 'foundry-resources-deployment'
  scope: rg
  params: {
    location: location
    suffix: suffix
    namePrefix: namePrefix
    aiDevGroupObjectId: aiDevGroupObjectId
    logAnalyticsWorkspaceId: logAnalyticsWorkspaceId
    aiModelDeploymentName: aiModelDeploymentName
    aiModelName: aiModelName
    aiModelFormat: aiModelFormat
    aiModelVersion: aiModelVersion
    aiModelSkuName: aiModelSkuName
    aiModelSkuCapacity: aiModelSkuCapacity
    storageSkuName: storageSkuName
    storageAccessTier: storageAccessTier
    kvSoftDeleteRetentionDays: kvSoftDeleteRetentionDays
    appInsightsRetentionDays: appInsightsRetentionDays
    aiServicesSkuName: aiServicesSkuName
  }
}

output resourceGroupName string = rg.name
output suffix string = suffix
output storageAccountName string = resources.outputs.storageAccountName
output keyVaultName string = resources.outputs.keyVaultName
output appInsightsName string = resources.outputs.appInsightsName
output aiFoundryName string = resources.outputs.aiFoundryName
output aiProjectName string = resources.outputs.aiProjectName
output aiModelDeploymentName string = resources.outputs.aiModelDeploymentName
output foundryProjectEndpoint string = resources.outputs.foundryProjectEndpoint
output azureOpenAIEndpoint string = resources.outputs.azureOpenAIEndpoint
