// ════════════════════════════════════════════════════════════════
// main.bicep — Subscription-scoped entry point
// Creates the zolab-ai-<suffix> resource group and deploys all
// AI Foundry resources + RBAC via the resources module.
// ════════════════════════════════════════════════════════════════
targetScope = 'subscription'

@description('Object ID of the zolab-ai-dev Entra ID security group')
param aiDevGroupObjectId string

@description('Subscription ID of the Security subscription (hosts DIBSecCom LAW)')
param securitySubscriptionId string

@description('6-char alphanumeric suffix for resource naming (generated by deploy script)')
param suffix string

@description('Deployment name to create for the selected AI model')
param aiModelDeploymentName string

@description('AI model name resolved for the selected deployment')
param aiModelName string

@description('Model format resolved for the selected deployment')
param aiModelFormat string

@description('Azure OpenAI model version resolved for the selected deployment')
param aiModelVersion string

@description('SKU name for the selected AI model deployment')
param aiModelSkuName string

@description('SKU capacity for the selected AI model deployment')
param aiModelSkuCapacity int

@description('Location for all resources')
param location string = 'eastus2'

var resourceGroupName = 'zolab-ai-${suffix}'

resource rg 'Microsoft.Resources/resourceGroups@2024-11-01' = {
  name: resourceGroupName
  location: location
}

module resources 'modules/resources.bicep' = {
  name: 'foundry-resources-deployment'
  scope: rg
  params: {
    location: location
    suffix: suffix
    aiDevGroupObjectId: aiDevGroupObjectId
    logAnalyticsWorkspaceId: '/subscriptions/${securitySubscriptionId}/resourceGroups/Sentinel/providers/Microsoft.OperationalInsights/workspaces/DIBSecCom'
    aiModelDeploymentName: aiModelDeploymentName
    aiModelName: aiModelName
    aiModelFormat: aiModelFormat
    aiModelVersion: aiModelVersion
    aiModelSkuName: aiModelSkuName
    aiModelSkuCapacity: aiModelSkuCapacity
  }
}

output resourceGroupName string = rg.name
output suffix string = suffix
output storageAccountName string = resources.outputs.storageAccountName
output keyVaultName string = resources.outputs.keyVaultName
output appInsightsName string = resources.outputs.appInsightsName
output aiFoundryName string = resources.outputs.aiFoundryName
output aiProjectName string = resources.outputs.aiProjectName
output aiModelDeploymentName string = resources.outputs.aiModelDeploymentName
output foundryProjectEndpoint string = resources.outputs.foundryProjectEndpoint
output azureOpenAIEndpoint string = resources.outputs.azureOpenAIEndpoint
